name: fl_clash
description: A multi-platform proxy client based on ClashMeta, simple and easy to use, open-source and ad-free.
publish_to: 'none'
version: 0.8.92+2026020201
environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: '>=3.3.10 <3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: 2.0.11
  path: 1.8.2
  shared_preferences: 2.0.15
  window_manager: 0.3.0
  dynamic_color: 1.5.4
  proxy:
    path: plugins/proxy
  window_ext:
    path: plugins/window_ext
  launch_at_startup: 0.2.2
  json_annotation: 4.7.0
  file_picker: 5.2.10
  mobile_scanner: 2.1.0
  app_links: 3.4.3
  win32_registry: 1.0.2
  tray_manager: 0.2.0
  collection: 1.17.0
  animations: 2.0.7
  package_info_plus: 3.1.2
  url_launcher: 6.1.7
  freezed_annotation: 2.2.0
  image_picker: 0.8.6+4
  ffi: 2.0.1
  webdav_client: 1.1.8
  dio: 4.0.6
  win32: 3.1.4
  re_editor: 0.1.1
  re_highlight: 0.0.3
  archive: 3.3.6
  emoji_regex: 0.0.5
  hotkey_manager: 0.1.7
  device_info_plus: 8.2.2
  connectivity_plus: 3.0.3
  screen_retriever: 0.1.9
  defer_pointer: 0.0.2
  flutter_riverpod: 2.3.6
  riverpod_annotation: 2.1.1
  riverpod: 2.3.6
  material_color_utilities: 0.1.5
  flutter_js: 0.6.0
  flutter_svg: 1.1.6
  flutter_cache_manager: 3.3.0
  crypto: 3.0.2
  yaml: 3.1.1
  drift: 2.4.2
dependency_overrides:
  analyzer: 5.4.0
  collection: 1.17.0
  custom_lint_core: 0.2.10
  ffi: 2.0.1
  re_editor:
    path: third_party/re_editor_compat
  url_launcher_macos: 3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  json_serializable: 6.5.4
  build_runner: 2.3.3
  args: 2.3.1
  freezed: 2.3.2
  riverpod_generator: 2.1.4

  drift_dev: 2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/fonts/
    - assets/images/
    - assets/images/avatar/
    - assets/images/empty/
    - assets/images/icon/
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
    - family: Twemoji
      fonts:
        - asset: assets/fonts/Twemoji.Mozilla.ttf
    - family: Icons
      fonts:
        - asset: assets/fonts/Icons.ttf
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: arb
  output_dir: lib/l10n
